language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
dist: trusty
sudo: false
install:
  - npm ci
before_deploy:
  - npm run build
  - rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: mcdevitt-swapi
  api_key:
    secure: "JhPco6tUcLJ606bbHOGdBfVuouAK6Gw3Jgawri8H5gvLbivzrB/OhJULUa7jknOXh57CyuRtOFJsA7pcMhBntmk7kJFfVcry8F/GfeQPU4NiaMhBZASDwZKPdg00aWAxpaWWKsy0PE9WKhCWR/LAqRXLHT7Iblmq/z4XY2NBNV1r37ltIcNa6MdnBwEsFAbkv2ATIlahUx0AyrGzlwb4EbWjo3z5ryWD2K4lAr0F6PP4ekbqVoC3QHST9f2RFe2jE6Pud1Qc1yZH/3nmdK7Gket5m87nf+VAI/tWk24aV9g6UO8AUn/L3PV+Sz8p05qIKl+JIT072NoTgT4yQVS0X7Gd27UzUOIyHjmUR5sCaBpkEC4SHt3yV2PrA5QxMw248tYZS0M1Ed4ks7Bug+wVbjSX16Nrl4RjFG+AgXv4Gu0QdhPQ2sh7uVg2A8iIu1E7uVcERktPXJRd4FSa+OEkukL/Qd8klGP17ZZOI/pLPCxP60xG2Dfs1h3UilC3BLnASvKe3p7eIDVkfhlOhS/QL5/lM4tXwGBUcRsjou2/vU/iiJX1BuyRUh7octqAJUqtnUkkBwirRc0Ri7oHPxsX740gNGHZ+sprdH+iB+D5DzQBdRVgst6nUk7IZslulIYh8/eW05/EiPt3WKQR11MnUqixYRjXD+2xYOEjmBVFrV0="
